name: Build app and deploy to aliyun
on:
  push:
    branches:
      - master
  workflow_dispatch:    # 核心：开启手动触发（无参数版）
    # 可选：添加自定义参数（比如部署不同环境）
    inputs:
      environment:
        description: '部署环境（prod/test）'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.0.0'

    - name: Install npm dependencies
      run: npm install -legacy-peer-deps

    - name: Run build task
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.1.1
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rlgoDzvc --delete'
          SOURCE: 'dist Dockerfile docker.sh nginx.conf'
          REMOTE_HOST: ${{ secrets.ECS_HOST }}
          REMOTE_USER: ${{ secrets.ECS_USERNAME }}
          TARGET: ${{ secrets.SERVER_TARGET }}
          SCRIPT_BEFORE: ls

    - name: Run Docker Commands on Server
      uses: appleboy/ssh-action@v0.1.7
      with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_TARGET }}
            sh docker.sh
